apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresh-sa
  namespace: web-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "create", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-manager-role
subjects:
  - kind: ServiceAccount
    name: ecr-refresh-sa
    namespace: web-proxy
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-refresh-job
  namespace: web-proxy
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-refresh-sa
          containers:
          - name: ecr-refresh
            image: google/cloud-sdk:alpine
            command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache aws-cli curl
              if ! command -v kubectl &> /dev/null; then
                  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                  chmod +x kubectl
                  mv kubectl /usr/local/bin/
              fi
              
              TOKEN=$(aws ecr get-login-password --region ap-northeast-2)
              
              # 1. tomcat-member (엑셀 네임스페이스 반영)
              kubectl delete secret ecr-cred-member -n tomcat-member --ignore-not-found
              kubectl create secret docker-registry ecr-cred-member --docker-server=820313036770.dkr.ecr.ap-northeast-2.amazonaws.com --docker-username=AWS --docker-password=$TOKEN -n tomcat-member

              # 2. tomcat-board (엑셀 네임스페이스 반영)
              kubectl delete secret ecr-cred-board -n tomcat-board --ignore-not-found
              kubectl create secret docker-registry ecr-cred-board --docker-server=820313036770.dkr.ecr.ap-northeast-2.amazonaws.com --docker-username=AWS --docker-password=$TOKEN -n tomcat-board

              # 3. ingress-nginx
              kubectl delete secret ecr-cred-nginx -n ingress-nginx --ignore-not-found
              kubectl create secret docker-registry ecr-cred-nginx --docker-server=820313036770.dkr.ecr.ap-northeast-2.amazonaws.com --docker-username=AWS --docker-password=$TOKEN -n ingress-nginx
              
              echo "All secrets refreshed!"
            envFrom:
            - secretRef:
                name: aws-secret
          restartPolicy: OnFailure
