apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-board-hpa
  namespace: ingress-nginx
  labels:
    app: nginx-board
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-board-deploy
  
  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40

    - type: Pods
      pods:
        metric:
          name: http_requests_per_second 
        target:
          type: AverageValue
          averageValue: 50
