apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-member-hpa
  namespace: ingress-nginx
  labels:
    app: nginx-member
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-member-deploy
  
  minReplicas: 2
  maxReplicas: 4

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

