apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-board-hpa
  namespace: tomcat-board
  labels:
    app: tomcat-board
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat-board-deploy
  
  minReplicas: 4
  maxReplicas: 20
  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
          
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 50
          
    - type: Pods
      pods:
        metric:
          name: tomcat_threadpool_queue_size
        target:
          type: AverageValue
          averageValue: 20
