apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-board-hpa
  namespace: tomcat-board
  labels:
    app: tomcat-board
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat-board-deploy

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
