apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-member-deploy
  namespace: tomcat-member
  labels:
    app: tomcat-member
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: tomcat-member
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: tomcat-member
    spec:
      # [1] Pod Anti-Affinity (Soft): "가능하면 겹치지 마라"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: tomcat-member
                topologyKey: "kubernetes.io/hostname"

      # [2] Topology Spread Constraints: "어쩔 수 없이 겹치면 비율을 맞춰라"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: tomcat-member

      imagePullSecrets:
        - name: ecr-cred-member

      containers:
        - name: tomcat-member-container
          image: 820313036770.dkr.ecr.ap-northeast-2.amazonaws.com/member-service:v1.3
          imagePullPolicy: Always

          # [3] Graceful Shutdown: 10초 대기
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]

          ports:
            - containerPort: 8080
          
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: tomcat-member-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tomcat-member-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tomcat-member-secret
                  key: DB_PASSWORD
            - name: CATALINA_OPTS
              value: "-Dspring.profiles.active=prod -Denv=prod"
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=prod -Denv=prod"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
