apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-plain-projects
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/vanillaturtlechips/streets-argocd.git"
        revision: main
        directories:
          - path: "projects/*"   # streets-argocd 리포지토리 안의 projects 폴더를 감지
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      sources:
      - repoURL: "https://github.com/vanillaturtlechips/streets-argocd.git"
        targetRevision: main
        path: '{{path}}'         # 예: projects/tomcat-board
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}' # 예: tomcat-board 네임스페이스로 배포